name: Generate Release Notes

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Create Release (generate release notes)
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Create or update GitHub Release (generate release notes)
        uses: peter-evans/create-or-update-release@v4
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
